### PR TITLE
[ENH] accepts `--output-layout` argument

### PR DESCRIPTION
**Pull request by zhao-cy**
BIDS Apps like fMRIPrep and QSIPrep would create a new folder within the designated output folder, e.g., new folders like `fmriprep` and `freesurfer` for fMRIPrep, and `qsiprep` for QSIPrep. So I added creating `fmriprepfake` folder here.

I've updated the version to `0.1.1` and pushed to [my personal docker hub repo](https://hub.docker.com/repository/docker/chenyingzhao/fmriprep_fake/general). For other changes please see the updated `README.md`.

Notes added on 7/13/2023: After talking w/ Dorota, I realized that this is not necessary the case for fMRIPrep, esp its recent updated output layout.

### CODE REVIEW

**Comment by zhao-cy** [comment]
TODO for myself: add `--output-layout legacy` option (which will follow fmriprep's legacy output layout) before merging this PR.

**Comment by zhao-cy** [comment]
In this PR, I made several enhancements regarding output layout and Docker image:

* `fmriprep-fake` accepts argument `--output-layout` now. - this will close issue #5 
  * Currently `--output-layout bids` (or not to specify) would work similar to latest fMRIPrep's output layout;
  * whereas `--output-layout legacy` is different from how fMRIPrep would generate when `legacy`, i.e., two folders: `fmriprep` and `freesurfer`. Code for `bids` is largely reused for this case.
* Generates `log` folder (within `sub-*` folder) now. This `log` folder is different from `logs` folder.
* Docker image uses multi-arch to build, so the Docker image would also work on Mac M1 laptops. 
* `README.md` in the github repo has been updated accordingly.

**Comment by djarecka** [comment]
@zhao-cy - thank you for the changes!

Could you please add to the README how people should use the 2 scripts you added: `prep_docker` and `test`

**Comment by zhao-cy** [comment]
Yes definitely! I'll also update the `README.md` too! I'll let you know once I think it's ready to merge.

**Comment by zhao-cy** [comment]
Currently this updated version `0.1.2` is available on my personal docker hub: [`chenyingzhao/fmriprep_fake`](https://hub.docker.com/r/chenyingzhao/fmriprep_fake), but I think it would be better to have the latest version on your account. If you do so, as you'll re-build the docker image, I may recommend incrementing the version to `0.1.3`, so that we can make sure for each version number, there is only one possible version of Docker image. Let me know what you think?

**Comment by zhao-cy** [comment]
@djarecka I think this is ready to merge! Please note my previous comments above. Thanks!

**Comment by djarecka** [comment]
thank you @zhao-cy . I will test it on openmind and create a new image on my dockerhub this week

**Pull request merged**
